// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpinRallyBot;

#nullable disable

namespace SpinRallyBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20230528060033_AddPipelineState")]
    partial class AddPipelineState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SpinRallyBot.Models.PipelineState", b =>
                {
                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.HasKey("Command");

                    b.ToTable("PipelineStates");
                });
#pragma warning restore 612, 618
        }
    }
}
